[book]
title = "FTD"
description = "MDbook created for FTD"
authors = ["Wasif Shah"]
language = "en"

[rust]
edition = "2018"

[output.html]
site-url = "/ftd/"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
